### ISSUE TITLE
تحسينات على الريبو

### ISSUE THREAD

**Issue by Wouze** [AbdullahAlabbas/Quran-Bot#1]
اكتب هذا بالعربي لانك عربي

حبذا لو تزيل bearer_token من ملف keys، لان البعض يعتقد انه مطلوب وهو غير مطلوب.

كذلك حبذا لو تجعل فيه خيار يأخذ فقط consumer_key و consumer_secret ويقوم بعملية انشاء الرابط والتوثيق، اذا اعجبتك الفكرة اخبرني كي اعمل عليها واسوي pull request.

كذلك وجب التنبيه للمكتبات المستعمله مثل tweepy انك تحتاج تحملها.

اقولها من باب التحسينات وليس مشاكل في مشروعك.

بارك الله فيك وزادك خيرا وعلما.

**Comment by AbdullahAlabbas** [comment]
> اكتب هذا بالعربي لانك عربي
> 
> حبذا لو تزيل bearer_token من ملف keys، لان البعض يعتقد انه مطلوب وهو غير مطلوب.
> 
> كذلك حبذا لو تجعل فيه خيار يأخذ فقط consumer_key و consumer_secret ويقوم بعملية انشاء الرابط والتوثيق، اذا اعجبتك الفكرة اخبرني كي اعمل عليها واسوي pull request.
> 
> كذلك وجب التنبيه للمكتبات المستعمله مثل tweepy انك تحتاج تحملها.
> 
> اقولها من باب التحسينات وليس مشاكل في مشروعك.
> 
> بارك الله فيك وزادك خيرا وعلما.

اهلا ومعذرة على الرد المتأخر , سوي pull request ماعندي اي مشكلة و الله يعطيك العافية ماتقصر

**Comment by Wouze** [comment]
تمت 👍 
اذا اعجبك سو merge
